// vuejs/src/components/App.vue
<script>
  import ColumnContainer from './ColumnContainer'

  export default {
    data: function () {
      return {
        columns: [],
        tasks: []
      }
    },
    mounted () {
      this.$root.$on('column-create', this.createColumn)
      this.$root.$on('column-delete', this.deleteColumn)
      this.$root.$on('task-create', this.createTask)
      this.$root.$on('task-delete', this.deleteTask)
      this.$root.$on('move-task', this.moveTask)
    },
    methods: {
      createColumn: function (name) {
        this.columns.push({
          id: this.columns.length + 1,
          label: name
        })
      },
      deleteColumn: function (cid) {
        this.columns = this.columns.filter(column => {
          return column.id !== cid
        })
      },
      createTask: function (cid, title, description) {
        this.tasks.push({
          column: cid,
          id: this.tasks.length + 1,
          title,
          description
        })
      },
      deleteTask: function (tid) {
        this.tasks = this.tasks.filter(task => {
          return task.id !== tid
        })
      },
      moveTask: function (tid, newCid) {
        this.tasks = this.tasks.map(task => {
          if (task.id !== tid) return task
          task.column = newCid
          return task
        })
      }
    },
    components: {
      ColumnContainer
    }
  }
</script>

<template>
  <div class="container">
    <header class="container--header">
      <h1>Vue.js Planner</h1>
    </header>
    <div class="appContainer">
      <column-container :columns="columns" :tasks="tasks"></column-container>
    </div>
  </div>
</template>

<style scoped>
</style>

// react/src/components/App/App.js
import React from 'react'
import './App.scss'
import ColumnContainer from '../ColumnContainer/ColumnContainer'

class App extends React.Component {
  constructor (props) {
    super(props)

    this.state = {
      columns: [],
      tasks: []
    }

    this.handlers = {
      createColumn: this.createColumn.bind(this),
      deleteColumn: this.deleteColumn.bind(this),
      createTask: this.createTask.bind(this),
      deleteTask: this.deleteTask.bind(this),
      moveTask: this.moveTask.bind(this)
    }
  }

  createColumn (columnName = 'Unknown') {
    const nextId = this.state.columns.length + 1
    const newColumns = [
      ...this.state.columns,
      {
        id: nextId,
        label: columnName
      }
    ]

    return this.setState({
      columns: newColumns
    })
  }

  deleteColumn (columnId) {
    // For now, let's just orphan tasks.
    const tasksInColumn = this.state.tasks.filter(task => {
      return task.column === columnId
    })

    tasksInColumn.forEach(taskInColumn => {
      this.deleteTask(taskInColumn.id)
    })

    const remainingColumns = this.state.columns.filter(column => {
      return columnId !== column.id
    })

    return this.setState({
      columns: remainingColumns
    })
  }

  createTask (columnId, taskTitle, taskDescription) {
    const nextId = this.state.tasks.length + 1
    return this.setState({
      tasks: [
        ...this.state.tasks,
        {
          id: nextId,
          column: columnId,
          title: taskTitle,
          description: taskDescription
        }
      ]
    })
  }

  deleteTask (taskId) {
    const remainingTasks = this.state.tasks.filter(task => {
      return taskId !== task.id
    })

    return this.setState({
      tasks: remainingTasks
    })
  }

  moveTask (taskId, newColumnId) {
    let tasks = this.state.tasks.map((task, index) => {
      if (task.id === taskId) task.column = newColumnId
      return task
    })

    return this.setState({
      tasks: tasks
    })
  }

  render () {
    return (
      <div className="container">
        <header className="container--header">
          <h1>React Planner</h1>
        </header>
        <div className="appContainer">
          <ColumnContainer columns={this.state.columns}
            tasks={this.state.tasks}
            handlers={this.handlers} />
        </div>
      </div>
    )
  }
}

export default App
