// react/src/components/Task/Task.js
import React from 'react'
import './Task.scss'

class Task extends React.Component {
  constructor (props) {
    super(props)
    this.handleDragStart = this.handleDragStart.bind(this)
  }

  handleDragStart (event) {
    event.dataTransfer.setData('text', JSON.stringify(this.props.task))
  }

  render () {
    return (
      <article className="task task" draggable="true" onDragStart={this.handleDragStart}>
        <button onClick={() => this.props.deleteTask(this.props.task.id)} type="button" className="close" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h3 className="task__title">{this.props.task.title}</h3>
        <p className="task__description">
          {this.props.task.description}
        </p>
      </article>
    )
  }
}

export default Task

// angular/src/app/task/task.component.ts
import { Component, Input } from '@angular/core';
import { StateService } from '../state.service'
import { Task } from '../types';

@Component({
  selector: 'app-task',
  templateUrl: './task.component.html',
  styleUrls: ['./task.component.scss']
})

export class TaskComponent {
  @Input() key: number
  @Input() task: Task

  constructor(readonly stateService: StateService) {
    // Nothing to see here.
  }

  deleteTask () {
    this.stateService.removeTask(this.task.id)
  }

  handleDragStart ($event: DragEvent) {
    $event.dataTransfer.setData('text', JSON.stringify(this.task))
  }
}

<article class="task" draggable="true" (dragstart)="handleDragStart($event)">
  <button (click)="deleteTask" type="button" class="close" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
  <h3 class="task__title">{{task.title}}</h3>
  <p class="task__description">{{task.description}}</p>
</article>
