// vuejs/src/components/Task.vue
<script>
  export default {
    data () {
      return {}
    },
    methods: {
      deleteTask: function (tid) {
        this.$root.$emit('task-delete', tid)
      },
      handleDragStart: function (event) {
        event.dataTransfer.setData('text', JSON.stringify(this.task))
      }
    },
    props: {
      task: Object
    },
    components: {}
  }
</script>

<template>
  <article class="task" draggable="true" @dragstart="handleDragStart($event)">
    <button @click="deleteTask(task.id)" type="button" class="close" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <h3 class="task__title">{{ task.title }}</h3>
    <p class="task__description">{{ task.description }}</p>
  </article>
</template>

<style scoped>
</style>

// react/src/components/Task/Task.js
import React from 'react'
import './Task.scss'

class Task extends React.Component {
  constructor (props) {
    super(props)
    this.handleDragStart = this.handleDragStart.bind(this)
  }

  handleDragStart (event) {
    event.dataTransfer.setData('text', JSON.stringify(this.props.task))
  }

  render () {
    return (
      <article className="task task" draggable="true" onDragStart={this.handleDragStart}>
        <button onClick={() => this.props.deleteTask(this.props.task.id)} type="button" className="close" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h3 className="task__title">{this.props.task.title}</h3>
        <p className="task__description">
          {this.props.task.description}
        </p>
      </article>
    )
  }
}

export default Task
