// react/src/components/Column/Column.js
import React from 'react'
import Task from '../Task/Task.js'
import TaskPlaceholder from '../TaskPlaceholder/TaskPlaceholder'
import './Column.scss'

class Column extends React.Component {
  constructor (props) {
    super(props)

    this.handleDrop = this.handleDrop.bind(this)
    this.handleDragover = this.handleDragover.bind(this)
  }

  handleDrop(event) {
    event.preventDefault()
    const data = event.dataTransfer.getData('text')
    const parsedData = JSON.parse(data)

    return this.props.handlers.moveTask(parsedData.id, this.props.data.id)
  }

  handleDragover(event) {
    event.preventDefault()
  }

  render () {
    const { deleteColumn } = this.props.handlers

    return (
      <section className="column col-3" onDragOver={this.handleDragover} onDrop={this.handleDrop}>
        <div className="column__panel">
          <div className="column__panel-heading">
            <button onClick={() => deleteColumn(this.props.data.id)} type="button" className="close" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
            <h2 className="column__panel-title">
              {this.props.data.label} {this.props.tasks.length ? `(${this.props.tasks.length})` : ''}
            </h2>
          </div>

          <div className="column__panel-content">
            {this.props.tasks.map(task => {
              return <Task key={task.id} task={task} handlers={this.props.handlers} />
            })}
            <TaskPlaceholder columnId={this.props.data.id} handlers={this.props.handlers} />
          </div>
        </div>
      </section>
    )
  }
}

export default Column

// angular/src/app/column/column.component.ts
import { Component, Input } from '@angular/core';
import { StateService } from '../state.service'
import { Column, Task } from '../types';

@Component({
  selector: 'app-column',
  templateUrl: './column.component.html',
  styleUrls: ['./column.component.scss']
})

export class ColumnComponent {
  @Input() key: number
  @Input() column: Column

  constructor(readonly stateService: StateService) {
    // Nothing to see here.
  }

  get columnTasks (): Task[] {
    const columnTasks = this.stateService.getTasks().filter((task) => task.column === this.column.id)
    return columnTasks
  }

  get columnTitle (): string {
    const allTasks = this.stateService.getTasks()
    const tasksInColumn = allTasks.filter((task) => task.column === this.column.id)
    return `${this.column.label} <sup>${tasksInColumn.length}</sup>`
  }

  deleteColumn () {
    this.stateService.removeColumn(this.column.id)
  }

  handleDrop ($event: DragEvent) {
    $event.preventDefault()
    const data = $event.dataTransfer.getData('text')
    const parsedData = JSON.parse(data)

    this.stateService.moveTask(parsedData.id, this.column.id)
  }

  handleDragover ($event: Event) {
    $event.preventDefault()
  }
}

<!-- <section class="column col-3" @dragover.prevent="" @drop.prevent="handleDrop($event)"> -->
<section class="column" (drop)="handleDrop($event)" (dragover)="handleDragover($event)">
  <div class="column__panel">
    <div class="column__panel-heading">
      <button (click)="deleteColumn()" type="button" class="close" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      <h2 class="column__panel-title" [innerHtml]="columnTitle"></h2>
      <hr />
    </div>

    <div class="column__panel-content">
      <app-task *ngFor="let task of columnTasks" [key]="task.id" [task]="task"></app-task>
      <app-task-placeholder [cid]="column.id"></app-task-placeholder>
    </div>
  </div>
</section>
