// vuejs/src/components/ColumnPlaceholder.vue
<script>
  export default {
    data () {
      return {
        isEditing: false,
        name: ''
      }
    },
    methods: {
      createColumn: function () {
        this.$root.$emit('column-create', this.name)
        this.isEditing = false
        this.name = ''
      },
      toggleEditing: function () {
        this.isEditing = !this.isEditing
      }
    },
    props: {},
    components: {}
  }
</script>

<template>
  <section class="column col-3">
    <div class="column__panel column__panel--placeholder">
      <span v-if="!isEditing" @click="toggleEditing()">Click to add column...</span>
      <div v-if="isEditing">
        <div class="input-group">
          <input type="text" v-model="name" class="form-control" placeholder="Column name" />
          <div class="input-group-append">
            <button v-if="name.length" @click="createColumn()" class="btn btn-success" type="button">Create</button>
            <button v-if="!name.length" @click="toggleEditing()" class="btn btn-danger" type="button">Cancel</button>
          </div>
        </div>
      </div>
    </div>
  </section>
</template>

<style scoped>
</style

// react/src/components/ColumnPlaceholder/ColumnPlaceholder.js
import React from 'react'
import '../column/column.scss'

class ColumnPlaceholder extends React.Component {
  constructor (props) {
    super(props)
    this.state = {
      isEditing: false,
      columnName: ''
    }

    this.toggleEditingState = this.toggleEditingState.bind(this)
    this.handleInput = this.handleInput.bind(this)
    this.createColumn = this.createColumn.bind(this)
  }

  toggleEditingState () {
    let currentState = this.state.isEditing
    this.setState({
      isEditing: !currentState
    })
  }

  handleInput (event) {
    event.preventDefault()
    this.setState({
      columnName: event.target.value
    })
  }

  createColumn (event) {
    event.preventDefault()
    this.props.createColumn(this.state.columnName)
    this.setState({
      isEditing: false,
      columnName: ''
    })
  }

  render () {
    return (
      <section className="column col-3">
        <div className="column__panel column__panel--placeholder">
          {!this.state.isEditing && (
            <p onClick={this.toggleEditingState}>Click to add column...</p>
          )}
          {this.state.isEditing && (
            <div className="input-group mb-3">
              <input onInput={this.handleInput} type="text" className="form-control" placeholder="Column name" />
              <div className="input-group-append">
                {this.state.columnName.length
                  ? <button onClick={this.createColumn} className="btn btn-success" type="button">Create</button>
                  : <button onClick={this.toggleEditingState} className="btn btn-danger" type="button">Cancel</button>
                }
              </div>
            </div>
          )}
        </div>
      </section>
    )
  }
}

export default ColumnPlaceholder
