// react/src/components/ColumnContainer/ColumnContainer.js
import React from 'react'
import './ColumnContainer.scss'
import Column from '../Column/Column.js'
import ColumnPlaceholder from '../ColumnPlaceholder/ColumnPlaceholder'

class ColumnContainer extends React.Component {
  constructor(props) {
    super(props)
    this.getTasksForColumn = this.getTasksForColumn.bind(this)
  }

  getTasksForColumn (columnId) {
    return this.props.tasks.filter((task) => {
      return task.columnId === columnId
    })
  }

  render () {
    return (
      <main className="columnContainer">
        <em className="columnContainer__summary">You have used {this.props.columns.length} out of a possible 4 columns.</em>
        <div className="columnContainer__content row">
          {this.props.columns.map((column, index) => {
            return <Column key={index} data={column} tasks={this.getTasksForColumn(column.id)} />
          })}
          {this.props.columns.length < 4 && (
            <ColumnPlaceholder />
          )}
        </div>
      </main>
    )
  }
}

export default ColumnContainer

// angular/src/app/column-container/column-container.component.ts
import { Component } from '@angular/core';
import { StateService } from '../state.service'

@Component({
  selector: 'app-column-container',
  templateUrl: './column-container.component.html',
  styleUrls: ['./column-container.component.scss']
})

export class ColumnContainerComponent {
  constructor(readonly stateService: StateService) {
    // Nothing to see here.
  }
}

<main class="columnContainer">
  <em class="columnContainer__summary">You have used {{stateService.getColumns().length}} out of a possible 4 columns.</em>
  <div class="columnContainer__content row">
    <app-column *ngFor="let column of stateService.getColumns(); index as i" [key]="i" [column]="column"></app-column>
    <app-column-placeholder *ngIf="stateService.getColumns().length < 4"></app-column-placeholder>
  </div>
</main>
