// react/src/components/Column/Column.js
import React from 'react'
import Task from '../Task/Task.js'
import TaskPlaceholder from '../TaskPlaceholder/TaskPlaceholder'
import './Column.scss'
import PropTypes from 'prop-types'

class Column extends React.Component {
  constructor (props) {
    super(props)

    this.handleDrop = this.handleDrop.bind(this)
    this.handleDragover = this.handleDragover.bind(this)
  }

  handleDrop(event) {
    event.preventDefault()
    const data = event.dataTransfer.getData('text')
    const parsedData = JSON.parse(data)

    return this.props.handlers.moveTask(parsedData.id, this.props.data.id)
  }

  handleDragover(event) {
    event.preventDefault()
  }

  render () {
    const { deleteColumn } = this.props.handlers

    return (
      <section className="column col-3" onDragOver={this.handleDragover} onDrop={this.handleDrop}>
        <div className="column__panel">
          <div className="column__panel-heading">
            <button onClick={() => deleteColumn(this.props.data.id)} type="button" className="close" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
            <h2 className="column__panel-title">
              {this.props.data.label} {this.props.tasks.length ? `(${this.props.tasks.length})` : ''}
            </h2>
            <hr/>
          </div>

          <div className="column__panel-content">
            {this.props.tasks.map(task => {
              return <Task key={task.id} task={task} handlers={this.props.handlers} />
            })}
            <TaskPlaceholder columnId={this.props.data.id} handlers={this.props.handlers} />
          </div>
        </div>
      </section>
    )
  }
}

Column.propTypes = {
  data: PropTypes.object,
  tasks: PropTypes.array,
  handlers: PropTypes.object
}

export default Column

// vuejs/src/components/Column.vue
<script>
  import Task from './Task'
  import TaskPlaceholder from './TaskPlaceholder'

  export default {
    data () {
      return {}
    },
    computed: {
      columnTitle: function () {
        if (this.tasks.length) return `${this.column.label} (${this.tasks.length})`
        return this.column.label
      }
    },
    methods: {
      deleteColumn: function (id) {
        this.$root.$emit('column-delete', id)
      },
      handleDrop: function (event) {
        const eventData = event.dataTransfer.getData('text')
        const parsedTask = JSON.parse(eventData)
        this.$root.$emit('move-task', parsedTask.id, this.column.id)
      }
    },
    components: {
      Task,
      TaskPlaceholder
    },
    props: {
      column: Object,
      tasks: Array
    }
  }
</script>

<template>
  <section class="column col-3" @dragover.prevent="" @drop.prevent="handleDrop($event)">
    <div class="column__panel">
      <div class="column__panel-heading">
        <button @click="deleteColumn(column.id)" type="button" className="close" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h2 className="column__panel-title">
          {{ columnTitle }}
        </h2>
        <hr/>
      </div>

      <div className="column__panel-content">
        <task v-for="task in tasks" :key="task.id" :task="task"></task>
        <task-placeholder :cid="column.id"></task-placeholder>
      </div>
    </div>
  </section>
</template>

<style scoped>
</style
