// vuejs/src/components/TaskPlaceholder.vue
<script>
  export default {
    data () {
      return {
        isEditing: false,
        title: '',
        description: ''
      }
    },
    methods: {
      toggleEditing: function () {
        this.isEditing = !this.isEditing
      },
      createTask: function () {
        this.$root.$emit('task-create', this.cid, this.title, this.description)
        this.isEditing = false
        this.title = ''
        this.description = ''
      }
    },
    props: {
      cid: Number
    },
    components: {}
  }
</script>

<template>
  <article class="task task--placeholder">
    <span v-if="!isEditing" @click="toggleEditing()">Click to add task...</span>
    <div v-if="isEditing" class="form-group">
      <input class="form-control mb-3" type="text" v-model="title" placeholder="What is the task?" />
      <textarea class="form-control mb-3" v-model="description" rows="3" placeholder="Any other details..."></textarea>
      <button v-if="title.length" @click="createTask(cid)" class="btn btn-block btn-success" type="button">Create</button>
      <button v-if="!title.length" @click="toggleEditing()" class="btn btn-block btn-danger" type="button">Cancel</button>
    </div>
  </article>
</template>

<style scoped>
</style>

// angular/src/app/task-placeholder/task-placeholder.component.ts
import { Component, Input } from '@angular/core';
import { StateService } from '../state.service'

@Component({
  selector: 'app-task-placeholder',
  templateUrl: './task-placeholder.component.html',
  styleUrls: ['./task-placeholder.component.scss']
})

export class TaskPlaceholderComponent {

  @Input() cid

  isEditing = false
  title = ''
  description = ''

  constructor(readonly stateService: StateService) {
    // Nothing to see here.
  }

  toggleEditing () {
    this.isEditing = !this.isEditing
  }

  createTask () {
    this.toggleEditing()

    this.stateService.addTask({
      id: this.stateService.getTasks().length + 1,
      column: this.cid,
      title: this.title,
      description: this.description
    })

    this.title = ''
    this.description = ''
  }

  updateTitle (title) {
    this.title = title
  }

  updateDescription (description) {
    this.description = description
  }
}

<article class="task task--placeholder">
  <span *ngIf="!isEditing" (click)="toggleEditing()">Click to add task...</span>
  <div *ngIf="isEditing" class="form-group">
    <input #typedTitle (keyup)="updateTitle(typedTitle.value)" class="form-control mb-3" type="text" placeholder="What is the task?" />
    <textarea #typedDescription (keyup)="updateDescription(typedDescription.value)" class="form-control mb-3" rows="3" placeholder="Any other details..."></textarea>
    <button *ngIf="title.length" (click)="createTask(cid)" class="btn btn-block btn-success" type="button">Create</button>
    <button *ngIf="!title.length" (click)="toggleEditing()" class="btn btn-block btn-danger" type="button">Cancel</button>
  </div>
</article>
