// react/src/components/ColumnPlaceholder/ColumnPlaceholder.js
import React from 'react'
import '../column/column.scss'

class ColumnPlaceholder extends React.Component {
  constructor (props) {
    super(props)
    this.state = {
      isEditing: false,
      columnName: ''
    }

    this.toggleEditingState = this.toggleEditingState.bind(this)
    this.handleInput = this.handleInput.bind(this)
    this.createColumn = this.createColumn.bind(this)
  }

  toggleEditingState () {
    let currentState = this.state.isEditing
    this.setState({
      isEditing: !currentState
    })
  }

  handleInput (event) {
    event.preventDefault()
    this.setState({
      columnName: event.target.value
    })
  }

  createColumn (event) {
    event.preventDefault()
    this.props.createColumn(this.state.columnName)
    this.setState({
      isEditing: false,
      columnName: ''
    })
  }

  render () {
    return (
      <section className="column col-3">
        <div className="column__panel column__panel--placeholder">
          {!this.state.isEditing && (
            <p onClick={this.toggleEditingState}>Click to add column...</p>
          )}
          {this.state.isEditing && (
            <div className="input-group mb-3">
              <input onInput={this.handleInput} type="text" className="form-control" placeholder="Column name" />
              <div className="input-group-append">
                {this.state.columnName.length
                  ? <button onClick={this.createColumn} className="btn btn-success" type="button">Create</button>
                  : <button onClick={this.toggleEditingState} className="btn btn-danger" type="button">Cancel</button>
                }
              </div>
            </div>
          )}
        </div>
      </section>
    )
  }
}

export default ColumnPlaceholder

// angular/src/app/column-placeholder/column-placeholder.component.ts
import { Component, ɵCompiler_compileModuleSync__POST_R3__ } from '@angular/core';
import { StateService } from '../state.service';

@Component({
  selector: 'app-column-placeholder',
  templateUrl: './column-placeholder.component.html',
  styleUrls: ['./column-placeholder.component.scss']
})

export class ColumnPlaceholderComponent {
  isEditing = false
  name = ''

  constructor(private stateService: StateService) {
    // Nothing to see here.
  }

  toggleEditing () {
    this.isEditing = !this.isEditing
  }

  createColumn () {
    this.toggleEditing()

    this.stateService.addColumn({
      id: this.stateService.getColumns().length + 1,
      label: this.name
    })

    this.name = ''
  }

  updateName (typedName) {
    this.name = typedName
  }
}

<section class="column">
  <div class="column__panel column__panel--placeholder">
    <span *ngIf="!isEditing" (click)="toggleEditing()">Click to add column...</span>
    <div *ngIf="isEditing">
      <div class="input-group">
        <input #typedName type="text" (keyup)="updateName(typedName.value)" (keyup.enter)="createColumn()" (blur)="createColumn()" class="form-control" placeholder="Column name" />
        <div class="input-group-append">
          <button *ngIf="name.length" (click)="createColumn()" class="btn btn-success" type="button">Create</button>
          <button *ngIf="!name.length" (click)="toggleEditing()" class="btn btn-danger" type="button">Cancel</button>
        </div>
      </div>
    </div>
  </div>
</section>
